ALTER TABLE image.extension ADD COLUMN "write" boolean;
UPDATE image.extension SET write=true;
ALTER TABLE image.extension ALTER COLUMN "write" SET NOT NULL;
ALTER TABLE image.extension ALTER COLUMN "write" SET DEFAULT false;

ALTER TABLE image.extension ADD COLUMN "web" boolean;
UPDATE image.extension SET web=true;
ALTER TABLE image.extension ALTER COLUMN "web" SET NOT NULL;
ALTER TABLE image.extension ALTER COLUMN "web" SET DEFAULT false;

-- remove all extensions without the used images
DELETE FROM image.extension WHERE name!='jpg' AND name!='gif' AND name!='png';
UPDATE image.extension SET description='Joint Photographic Experts Group JFIF format' WHERE name='jpg';
UPDATE image.extension SET description='CompuServe Graphics Interchange Format' WHERE name='gif';
UPDATE image.extension SET description='Portable Network Graphics' WHERE name='png';

INSERT INTO image.extension (name, mimetype, description, write, web, write, web) VALUES ('art','image/art','PFS: 1st Publisher',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('avs','image/avs','AVS X image',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('bmp','image/bmp','Microsoft Windows bitmap',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('cin','image/cin','Kodak Cineon Image Format',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('cur','image/x-win-bitmap','Microsoft Cursor Icon',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('cut','image/cut','DR Halo',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('dcm','image/dcm','Digital Imaging and Communications in Medicine (DICOM) image',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('dcx','image/dcx','ZSoft IBM PC multi-page Paintbrush image',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('dib','image/dib','Microsoft Windows Device Independent Bitmap',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('dng','image/dng','Digital Negative',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('dot','image/dot','Graph Visualization',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('dpx','image/dpx','SMPTE Digital Moving Picture Exchange',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('emf','image/emf','Microsoft Enhanced Metafile (32-bit)',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('fax','image/fax','Group 3 TIFF',true,false);
--INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('gif','image/gif','CompuServe Graphics Interchange Format',true,true);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('ico','image/vnd.microsoft.icon','Microsoft icon',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('jng','image/jng','Multiple-image Network Graphics',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('jp2','image/jp2','JPEG-2000 JP2 File Format Syntax',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('jpc','image/jpc','JPEG-2000 Code Stream Syntax',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('jpe','image/jpeg','Joint Photographic Experts Group JFIF format',true,true);
--INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('jpg','image/jpeg','Joint Photographic Experts Group JFIF format',true,true);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('mif','image/miff','Magick image file format',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('mat','image/mat','MATLAB image format',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('mng','image/mng','Multiple-image Network Graphics',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('mpc','image/mpc','Magick Persistent Cache image file format',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('mtv','image/mtv','MTV Raytracing image format',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('mvg','image/mvg','Magick Vector Graphics',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('otb','image/otb','On-the-air Bitmap',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('pbm','image/pbm','Portable bitmap format (black and white)',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('pcd','image/pcd','Photo CD',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('pcx','image/pcx','ZSoft IBM PC Paintbrush file',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('pdb','image/pdb','Palm Database ImageViewer Format',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('pix','image/pix','Alias/Wavefront RLE image format',false,false);
--INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('png','image/png','Portable Network Graphics',true,true);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('pnm','image/pnm','Portable anymap',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('ppm','image/ppm','Portable pixmap format (color)',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('psd','application/x-photoshop','Adobe Photoshop bitmap file',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('pwp','image/pwp','Seattle File Works multi-image file',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('rad','image/rad','Radiance image file',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('rla','image/rla','Alias/Wavefront image file',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('rle','image/rle','Utah Run length encoded image file',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('sct','image/sct','Scitex Continuous Tone Picture',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('sfw','image/sfw','Seattle File Works image',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('sgi','image/sgi','Irix RGB image',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('sun','image/sun','SUN Rasterfile',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('svg','image/svg+xml','Scalable Vector Graphics',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('tga','image/tga','Truevision Targa image',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('tif','image/tiff','Tagged Image File Format',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('wmf','image/x-wmf','Windows Metafile',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('wpg','image/wpg','Word Perfect Graphics File',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('xbm','image/x-xbm','X Windows system bitmap, black and white only',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('xcf','image/xcf','GIMP image',false,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('xpm','image/x-xpm','X Windows system pixmap',true,false);
INSERT INTO image.extension (name, mimetype, description, write, web) VALUES ('xwd','image/x-xwd','X Windows system window dump',true,false);
